name: Qt WebAssembly CI 

on:
  push:
    branches: [ "main" ]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    # This is the "Magic" step: The job runs INSIDE your pre-built image
    container:
      image: ghcr.io/goovey/wasm-test/qt6-wasm:latest
      # We need to run as root inside the container to source emsdk easily
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile Application
        shell: bash
        run: |
          source /opt/emsdk/emsdk_env.sh
          qt-cmake -S . -B build -G Ninja
          cmake --build build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qt-wasm-release
          path: build/WasmTest*
